import type { DispatchFlowStage, DispatchTopic } from "./types";

export const dispatchFlowStages: DispatchFlowStage[] = [
  {
    num: 1,
    name: "信息收集",
    tag: "ANALYSTS",
    countLabel: "并行采集",
    footerChip: "独立简报 · 不互相干扰",
    agents: [
      {
        id: "fundamental_analyst",
        name: "基本面分析师",
        role: "Fundamentals",
        desc: "财务 / 内在价值 / red flags",
        avatarClass: "a-fund",
      },
      {
        id: "sentiment_analyst",
        name: "情绪分析师",
        role: "Sentiment",
        desc: "社交媒体 / 情绪打分",
        avatarClass: "a-sent",
      },
      {
        id: "news_analyst",
        name: "新闻分析师",
        role: "News",
        desc: "全球新闻 / 宏观 / 事件",
        avatarClass: "a-news",
      },
      {
        id: "technical_analyst",
        name: "技术分析师",
        role: "Technical",
        desc: "MACD / RSI / 价格模式",
        avatarClass: "a-tech",
      },
    ],
    detail: [
      { label: "输入", value: "4 类原始信号源" },
      { label: "流程", value: "4 名分析师并行 / 互不干扰" },
      { label: "输出", value: "4 份独立简报 + 证据链" },
    ],
  },
  {
    num: 2,
    name: "多空辩论",
    tag: "RESEARCHERS",
    countLabel: "多轮辩论",
    variant: "debate",
    footerChip: "多轮 debate · 拿出最强论据",
    agents: [
      {
        id: "bullish_researcher",
        name: "看多研究员",
        role: "Bullish",
        desc: "立论看多 / 守住牛市观点",
        avatarClass: "a-bull",
      },
      {
        id: "bearish_researcher",
        name: "看空研究员",
        role: "Bearish",
        desc: "立论看空 / 守住熊市观点",
        avatarClass: "a-bear",
      },
    ],
    detail: [
      { label: "输入", value: "4 分析师独立简报" },
      { label: "流程", value: "多轮立论 / 反驳 / 压力测试" },
      { label: "输出", value: "辩论纪要 + 双方核心证据" },
    ],
  },
  {
    num: 3,
    name: "交易方案",
    tag: "TRADER",
    countLabel: "综合输出",
    footerChip: "方向 · 时机 · 仓位 · 止损",
    agents: [
      {
        id: "trader",
        name: "交易员",
        role: "Trader",
        desc: "综合简报 + 辩论 → 可执行方案",
        avatarClass: "a-trade",
      },
    ],
    detail: [
      { label: "输入", value: "4 简报 + 多空辩论纪要" },
      { label: "决策", value: "方向 / 时机 / 仓位 / 止损" },
      { label: "边界", value: "失效条件 + 风险线" },
    ],
  },
  {
    num: 4,
    name: "风险审查",
    tag: "RISK REVIEW",
    countLabel: "三派审查",
    variant: "debate",
    footerChip: "波动 · 流动性 · 相关性",
    agents: [
      {
        id: "aggressive_reviewer",
        name: "激进派",
        role: "Aggressive",
        desc: "高仓位 / 追求最大收益",
        avatarClass: "a-aggr",
      },
      {
        id: "neutral_reviewer",
        name: "中立派",
        role: "Neutral",
        desc: "平衡仓位 / 风险均衡",
        avatarClass: "a-neut",
      },
      {
        id: "conservative_reviewer",
        name: "保守派",
        role: "Conservative",
        desc: "低仓位 / 守住下行风险",
        avatarClass: "a-cons",
      },
    ],
    detail: [
      { label: "维度", value: "波动性 / 流动性 / 相关性" },
      { label: "流程", value: "三派多轮辩论 / 修订方案" },
      { label: "输出", value: "含风险边界的最终建议" },
    ],
  },
  {
    num: 5,
    name: "最终决策",
    tag: "PORTFOLIO MANAGER",
    countLabel: "终审裁决",
    variant: "final",
    footerChip: "批准送执行 · 拒绝落档",
    agents: [
      {
        id: "portfolio_manager",
        name: "组合经理",
        role: "Portfolio Manager",
        desc: "全组合视角 · 二元裁决",
        avatarClass: "a-pm",
      },
    ],
    detail: [
      { label: "视角", value: "全组合 + 风险预算 + 相关性" },
      { label: "批准", value: "送交易所执行" },
      { label: "拒绝", value: "落档进入复盘库" },
    ],
  },
  {
    num: 6,
    name: "复盘沉淀",
    tag: "MEMORY LOOP",
    countLabel: "持续沉淀",
    variant: "memory",
    footerChip: "cross-run · reflection",
    agents: [
      {
        id: "memory_loop",
        name: "记忆回路",
        role: "Reflection",
        desc: "每次决策都让系统更聪明",
        avatarClass: "a-mem",
      },
    ],
    detail: [
      { label: "落盘", value: "决策档案全量存档" },
      { label: "回灌", value: "历史经验注入下次 prompt" },
      { label: "复利", value: "跨标的教训 / 越跑越懂" },
    ],
  },
];

export const dispatchTopics: DispatchTopic[] = [
  {
    id: "btc-live-market-check",
    symbol: "BTC",
    status: "active",
    title: "🔥 BTC live market check · BTC 距前低 0.35%，下方止损单密集",
    originalUrl: "#",
    startedAt: "19:22",
    progress: "当前进行到阶段 3",
    intensity: 3,
    trigger: {
      ticker: "$BTC",
      text: "Rewards Wallet 多链 swap campaign + ETF 24h 净流出 2.1 亿",
    },
    stages: [
      { id: "btc-stage-1", label: "阶段 1 · 信息收集", status: "done" },
      { id: "btc-stage-2", label: "阶段 2 · 多空辩论", status: "done" },
      { id: "btc-stage-3", label: "阶段 3 · 交易方案 · 进行中", status: "active" },
      {
        id: "btc-stage-4",
        label: "阶段 4-6 · 等待中",
        status: "pending",
        note: "风险审查 / PM 终审 / 复盘 按顺序触发",
      },
    ],
    messages: [
      {
        id: "btc-tech-1",
        stageId: "btc-stage-1",
        agentId: "technical_analyst",
        agentName: "技术分析师",
        time: "19:22",
        dataAge: "数据 526 秒前",
        mentions: [],
        content:
          "$BTC 现价 <b>80,730</b>，距 24h 低 80,537 仅 0.24%。下方止损单堆积，<b>失守 80,537 可能触发瀑布</b>。",
      },
      {
        id: "btc-news-1",
        stageId: "btc-stage-1",
        agentId: "news_analyst",
        agentName: "新闻分析师",
        time: "19:23",
        dataAge: "数据 530 秒前",
        mentions: ["@技术"],
        quote: {
          agentName: "技术",
          text: "失守 80,537 可能触发瀑布",
        },
        content:
          "Rewards Wallet 多链 swap 引入新流动性，但 24h 内 ETF 净流出 2.1 亿。<b>多空因素互抵</b>。",
      },
      {
        id: "btc-sentiment-1",
        stageId: "btc-stage-1",
        agentId: "sentiment_analyst",
        agentName: "情绪分析师",
        time: "19:23",
        dataAge: "数据 526 秒前",
        mentions: [],
        content: 'X 24h 情绪打分 <b>48 / 100</b>，从昨日 62 大幅回落。"恐慌"提及率上升 32%。',
      },
      {
        id: "btc-fundamental-1",
        stageId: "btc-stage-1",
        agentId: "fundamental_analyst",
        agentName: "基本面分析师",
        time: "19:24",
        dataAge: "数据 533 秒前",
        mentions: [],
        content: "链上长持地址余额 24h <b>−0.4%</b>，首次出现减仓信号。<b>结构开始动摇</b>。",
      },
      {
        id: "btc-bear-1",
        stageId: "btc-stage-2",
        agentId: "bearish_researcher",
        agentName: "看空研究员",
        time: "19:26",
        mentions: [],
        content: "情绪转空 + 链上减仓 + ETF 流出 + 关键位附近，<b>四向背离</b>。建议 SHORT 80,537 失守。",
      },
      {
        id: "btc-bull-1",
        stageId: "btc-stage-2",
        agentId: "bullish_researcher",
        agentName: "看多研究员",
        time: "19:27",
        mentions: ["@看空"],
        quote: {
          agentName: "看空",
          text: "四向背离，建议 SHORT 80,537 失守",
        },
        content: "情绪从 62 回落到 48 是正常修正，<b>不是恐慌</b>。新流动性可能抵消 ETF 流出。<b>等失守再确认</b>。",
      },
      {
        id: "btc-trader-typing",
        stageId: "btc-stage-3",
        agentId: "trader",
        agentName: "交易员",
        time: "19:31",
        mentions: [],
        content: "",
        typing: true,
      },
    ],
    strategy: {
      action: "wait",
      actionLabel: "分析中",
      name: "本次决策",
      meta: "3 个阶段已完成 · 交易员正在出方案 · 预计 1-2 分钟",
      entry: "待定",
      stopLoss: "待定",
      takeProfit: "待定",
      follow: {
        primaryLabel: "等待方案",
        primaryDisabled: true,
        secondaryLabel: "提醒我",
        watchCount: 77,
        followCount: 0,
        expiryNote: "等待出方案",
      },
    },
    defaultCollapsed: false,
  },
  {
    id: "eth-live-market-check",
    symbol: "ETH",
    status: "done",
    title: "📉 ETH live market check · 4h 失守 EMA50，CEX 净流入扩大",
    originalUrl: "#",
    startedAt: "18:10",
    progress: "28 分钟闭环",
    intensity: 4,
    trigger: {
      ticker: "$ETH",
      text: "ETH whale 转入 Binance 18.5M USD · 4h MACD 下穿零轴",
    },
    stages: [
      { id: "eth-stage-1", label: "阶段 1-2 · 信息收集 + 多空辩论", status: "done" },
      { id: "eth-stage-2", label: "阶段 3-4 · 交易方案 + 风险审查", status: "done" },
      { id: "eth-stage-3", label: "阶段 5 · 最终决策", status: "final" },
      { id: "eth-stage-4", label: "阶段 6 · 复盘沉淀", status: "done" },
    ],
    messages: [
      {
        id: "eth-tech-1",
        stageId: "eth-stage-1",
        agentId: "technical_analyst",
        agentName: "技术分析师",
        time: "18:11",
        mentions: [],
        content: "$ETH <b>2,548</b>。4h 失守 EMA50（2,560），下方支撑 2,460。<b>下行结构成立</b>。",
      },
      {
        id: "eth-bear-1",
        stageId: "eth-stage-1",
        agentId: "bearish_researcher",
        agentName: "看空研究员",
        time: "18:14",
        mentions: [],
        content: "技术 + 资金面双重背离，<b>清晰偏空 SHORT</b>。",
      },
      {
        id: "eth-bull-1",
        stageId: "eth-stage-1",
        agentId: "bullish_researcher",
        agentName: "看多研究员",
        time: "18:15",
        mentions: ["@看空"],
        quote: {
          agentName: "看空",
          text: "技术 + 资金面双重背离",
        },
        content: "承认短期偏空。<b>仅注意 2,460 是关键支撑</b>。",
      },
      {
        id: "eth-trader-1",
        stageId: "eth-stage-2",
        agentId: "trader",
        agentName: "交易员",
        time: "18:20",
        mentions: [],
        content: "方案 <b>SHORT</b>。入场 2,548-2,560 / 止损 2,610 / 止盈 2,460-2,400 / 仓位 6%。",
      },
      {
        id: "eth-neutral-1",
        stageId: "eth-stage-2",
        agentId: "neutral_reviewer",
        agentName: "中立派",
        time: "18:30",
        mentions: ["@保守 @激进"],
        content: "<b>采纳保守 6% · 拒绝加仓</b>。风险线 2,610 不动。",
      },
      {
        id: "eth-pm-1",
        stageId: "eth-stage-3",
        agentId: "portfolio_manager",
        agentName: "组合经理",
        time: "18:35",
        mentions: [],
        content: "<b>批准 SHORT</b>。组合对冲性 SHORT，风险预算未超限。<b>已送执行</b>。",
      },
      {
        id: "eth-memory-1",
        stageId: "eth-stage-4",
        agentId: "memory_loop",
        agentName: "记忆回路",
        time: "18:38",
        mentions: [],
        content: "已落盘 #s-4205。同标的 SHORT 30 日胜率 <b>58%</b>。经验已注入所有 agent prompt。",
      },
    ],
    strategy: {
      action: "short",
      actionLabel: "SHORT 6%",
      name: "已开仓",
      meta: "已开仓 18:35 · 当前盈亏 +0.8%",
      entry: "2,548 - 2,560",
      stopLoss: "2,610",
      takeProfit: "2,460 / 2,400",
      follow: {
        primaryLabel: "已跟单",
        primaryDisabled: true,
        secondaryLabel: "查看详情",
        watchCount: 142,
        followCount: 54,
      },
    },
    defaultCollapsed: true,
  },
  {
    id: "sol-live-market-check",
    symbol: "SOL",
    status: "pending",
    title: "⚡ SOL live market check · 区间震荡 + 链上活跃地址下行",
    originalUrl: "#",
    startedAt: "19:30",
    progress: "信息收集中",
    intensity: 1,
    trigger: {
      ticker: "$SOL",
      text: "SOL 168.4 区间震荡 24h · 链上活跃地址 −2.3%",
    },
    stages: [
      {
        id: "sol-stage-1",
        label: "阶段 1 · 信息收集 · 刚启动",
        status: "active",
        note: "情绪 / 新闻 分析师等待数据源就绪",
      },
      {
        id: "sol-stage-2",
        label: "阶段 2-6 · 等待中",
        status: "pending",
        note: "阶段 1 完成后按顺序触发",
      },
    ],
    messages: [
      {
        id: "sol-tech-1",
        stageId: "sol-stage-1",
        agentId: "technical_analyst",
        agentName: "技术分析师",
        time: "19:31",
        mentions: [],
        content: "$SOL <b>168.4</b>。24h −2.1%。阻力 175 / 支撑 165。区间震荡。",
      },
      {
        id: "sol-fundamental-typing",
        stageId: "sol-stage-1",
        agentId: "fundamental_analyst",
        agentName: "基本面分析师",
        time: "19:31",
        mentions: [],
        content: "",
        typing: true,
      },
    ],
    strategy: {
      action: "pending",
      actionLabel: "PENDING",
      name: "尚未决策",
      meta: "分析进行中 · 预计 2-3 分钟出方案",
      entry: "待定",
      stopLoss: "待定",
      takeProfit: "待定",
      follow: {
        primaryLabel: "等待决策",
        primaryDisabled: true,
        secondaryLabel: "提醒我",
        watchCount: 31,
        followCount: 0,
      },
    },
    defaultCollapsed: true,
  },
];
